routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/news', 'NewsController');
Route::put('/news/rate/{news}', 'NewsController@rate')->name('news.rate');

Route::resource('/image', 'ImageController');
Route::put('/image/rate/{image}', 'ImageController@rate')->name('image.rate');

Route::get('/rabbit', 'RabbitController@index')->name('rabbit');

app/News.php
<?php

namespace App;

use App\Contracts\HasRating;
use App\Traits\Searchable;
use App\Traits\Rateable;
use Illuminate\Database\Eloquent\Model;

class News extends Model implements HasRating
{
    use Rateable, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'body', 'author_id'
    ];
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreNewsRequest;
use App\Http\Requests\RateRequest;
use App\Http\Services\RateService;
use App\News;
use App\Repositories\NewsRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class NewsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->only('create');
        $this->middleware('auth')->only('store');
        $this->middleware('auth')->only('rate');
    }

    /**
     * Show the list of news.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request, NewsRepository $repository)
    {
        if ($request->has('search') && $request->input('search')) {
            $news = $repository->searchOnElasticsearch($request->input('search'));
            $ids = Arr::pluck($news['hits']['hits'], '_id');
            $newsList = News::whereIn('id', $ids)
                ->orderBy('created_at', 'desc')
                ->paginate(9);
        } else {
            $newsList = News::orderBy('created_at', 'desc')->paginate(9);
        }

        return view('news/index', [
            'newsList' => $newsList,
            'search' => $request->input('search'),
        ]);
    }

    /**
     * Show the form to create news.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function create()
    {
        return view('news/create');
    }

    /**
     * Save news.
     *
     * @return Boolean
     */
    public function store(StoreNewsRequest $request)
    {
        return News::create([
            'title' => $request->title,
            'body' => $request->body,
            'author_id' => $request->user()->id,
        ]);
    }

    /**
     * Show the news.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function show(News $news)
    {
        return view('news/show', [
            'news' => $news,
        ]);
    }

    /**
     * Rate the image.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $news
     * @return int
     */
    public function rate(Request $request, News $news): int
    {
        RateService::rate($news, $request->like);

        return $news->rate;
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">
    <h1>Создать новость</h1>

    <news-create-component />
  </div>

@endsection

resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">
    <h1>Список новостей</h1>

    <form>
        <div class="input-group mb-3">
            <input
              type="search"
              name="search"
              class="form-control"
              placeholder="Найти новости"
              aria-label="Найти новости"
              aria-describedby="basic-addon2"
              value="{{ $search }}"
            >
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Найти</button>
            </div>
        </div>
    </form>
    <div class="row">
      @foreach ($newsList as $news)
        <news-component
          :item="{{ $news }}"
          :is-rate="{{ $news->isRate() ? 1 : 0 }}"
          rate-url="{{ route('news.rate', $news->id) }}"
          url="{{ route('news.show', $news->id) }}"
          :is-auth="{{ auth()->check() ? 1 : 0 }}"
        ></news-component>
      @endforeach
    </div>

    <div class="float-left">
      {{ $newsList->links() }}
    </div>

    @auth
      <a class="btn btn-success float-right m-2" href="{{ route("news.create") }}">Создать новую статью</a>
    @endauth
  </div>

@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')

  <article>
    <div class="container">
      <h1 class="mt-5">{{ $news->title }}</h1>

      <div class="p-3 m-3 lead bg-white border"> {{ $news->body }}</div>
    </div>
  </article>

@endsection